---
# Update code deployment step
- name: ANSISTRANO | Ensure deployment base path exists
  file: state=directory recurse=yes path={{ ansistrano_deploy_to }}

- name: ANSISTRANO | Ensure releases folder exists
  file: state=directory recurse=yes path={{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}

- name: ANSISTRANO | Ensure shared elements folder exists
  file: state=directory recurse=yes path={{ ansistrano_deploy_to }}/shared

- name: ANSISTRANO | Get release timestamp
  command: date +%Y%m%d%H%M%S
  register: ansistrano_timestamp

- name: ANSISTRANO | Get release path
  command: echo "{{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}/{{ ansistrano_timestamp.stdout }}"
  register: ansistrano_release_path

- name: ANSISTRANO | Get releases path
  command: echo "{{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}"
  register: ansistrano_releases_path

- name: ANSISTRANO | RSYNC | Deploy using Rsync strategy
  include: update-code/rsync.yml
  when: ansistrano_deploy_via == 'rsync'

- name: ANSISTRANO | SCP | Deploy using SCP strategy
  include: update-code/copy.yml
  when: ansistrano_deploy_via == 'copy'

- name: ANSISTRANO | GIT | Deploy using Git strategy
  include: update-code/git.yml
  when: ansistrano_deploy_via == 'git'

- name: ANSISTRANO | S3 | Deploy using S3 strategy
  include: update-code/s3.yml
  when: ansistrano_deploy_via == 's3'

- name: ANSISTRANO | Copy release version into REVISION file
  shell: echo {{ ansistrano_timestamp.stdout }} > {{ ansistrano_release_path.stdout }}/REVISION

- name: ANSISTRANO | Touches up the release code
  shell: chmod -R -- g+w {{ ansistrano_release_path.stdout }} && chmod -R g+w {{ ansistrano_release_path.stdout }}
